const movieInfoList = [
  {
    id: 0,
    name: 'Tenet',
    release: 'Dec 04, 2020',
    duration: '2 hrs 31 mins',
    percentage: 80,
    votes: 29222,
    tags: ['action', 'thriller'],
  },
  {
    id: 1,
    name: 'Monster Hunter',
    release: 'Feb 05, 2021',
    duration: '1 hrs 39 mins',
    percentage: 69,
    votes: 290,
    tags: ['action', 'adventure', 'fantasy'],
  },
  {
    id: 2,
    name: 'Vijay The Master',
    release: 'Jan 14, 2021',
    duration: '2 hrs 58 mins',
    percentage: 89,
    votes: 6410,
    tags: ['action', 'thriller'],
  },
  {
    id: 3,
    name: 'Wonder Woman 1984',
    release: 'Dec 24, 2020',
    duration: '2hrs 31mins',
    percentage: 70,
    votes: 25388,
    tags: ['action', 'adventure', 'fantasy'],
  },
  {
    id: 4,
    name: 'Ramprasad Ki Tehrvi',
    release: 'Jan 01, 2021',
    duration: '1hrs 55mins',
    percentage: 74,
    votes: 1479,
    tags: ['comedy', 'drama', 'family'],
  },
  {
    id: 5,
    name: 'Madam Chief Minister',
    release: 'Jan 22, 2021',
    duration: '2hrs 04mins',
    percentage: 69,
    votes: 688,
    tags: ['drama', 'political'],
  },
  {
    id: 6,
    name: 'Ford v Ferrari',
    release: 'Nov 15, 2019',
    duration: '2hrs 35mins',
    percentage: 93,
    votes: 57558,
    tags: ['action', 'biography', 'drama'],
  },
  {
    id: 7,
    name: 'Zombie Reddy',
    release: 'Feb 05, 2021',
    duration: '2hrs 05mins',
    percentage: 89,
    votes: 2028,
    tags: ['action', 'comedy', 'horror'],
  },
  {
    id: 8,
    name: 'Suraj Pe Mangal Bhari',
    release: 'Nov 15, 2020',
    duration: '2hrs 21mins',
    percentage: 74,
    votes: 3774,
    tags: ['comedy', 'family'],
  },
  {
    id: 9,
    name: 'Trip',
    release: 'Feb 05, 2021',
    duration: '2hrs 01mins',
    percentage: 0,
    votes: 0,
    tags: ['comedy', 'horror'],
  },
];
